### ISSUE TITLE
Add grid radar

### ISSUE THREAD

**Issue by syedhamidali** [syedhamidali/radarx#51]
* radarx version:
* Python version:
* Operating System:

### Description

Try fast-barnes-py to perform gridding on radar data
### What I Did

**Comment by syedhamidali** [comment]
Hi @kmuehlbauer
 Which package provides faster gridding?
1. [Py-ART Example](https://radarx.readthedocs.io/en/latest/notebooks/gridding_rate_part1.html)
2. [fast-barnes-py Example](https://radarx.readthedocs.io/en/latest/notebooks/gridding_rate_part2.html)
3. [Wradlib Example](https://radarx.readthedocs.io/en/latest/notebooks/gridding_rate_part3.html)

I experimented with gridding rates and wondered if [fast-barnes-py](https://github.com/MeteoSwiss/fast-barnes-py) could beat the current methods. Here are the results. Wradlib is even faster, or I might have messed up the implementation somewhere :). What do you think?

**Comment by kmuehlbauer** [comment]
You'd also need to take the complexity of the calculations into account. 

It's great to see wradlib in first place, but it implements a simple IDW scheme which might not be that complex as the Barnes algorithm. 

Py-ART also uses Barnes weighting under the hood, there is an extensive parameter list on the `map_gates_to_grid` function. If you really want to make some considerations, a similar parameter set has to be used for all examples.

If there is interest, I can try to implement Barnes algorithm the wradlib way for better comparison.

**Comment by syedhamidali** [comment]
Yeah, that would be great. Meanwhile, I'll implement CAPPI and composite plotting accessors.
